---
title: "DataMethods"
author: "Susanna"
date: "2026-09-15"
output: html_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data and Methods

## Data

To answer the research questions, I make use of the Friendship and Identity in School (FIS) dataset [@leszczensky2022]. The data were collected in six waves between May 2013 and March 2017 among 9,292 adolescents at ten secondary schools in the German federal state North Rhine-Westphalia. A sampling frame of schools was developed based on the share of students with Turkish or otherwise foreign citizenship in order to capture settings with ample opportunity for interethnic contact. Participants were in the 5th, 6th, or 7th grade during the first wave. **add something about school transition**. Students filled in the paper questionnaire in-class, resulting in student response rates of 76.3%-87.8% per wave. Among other topics, participants were asked about various types of social relationships with peers within their same grade, enabling the construction of directed grade-level socionets.

### Dependent Variable: Friendship Network Evolution

A directed grade-level friendship network was constructed based on the peers each student nominated as their 'best friends'. Students could nominate up to ten best friends from within their class or other classes within the same grade. Only students who were in 5th grade, the first year of secondary school, during the first wave of data collection were included in this study.

*For the purpose of this course paper, only one of the participating grades was randomly selected: or I'll do a meta-analysis*

### Node attributes

**Group Identification**

Group identification was measured using the question: *"How do you see yourself?"*. Participants could choose between the options *only as German*, *more as German*, *both equally*, *more as a person from the country of origin of my family*, and *only as a person from the country of origin of my family*. Students were classified as members of one of four groups: non-migratised majority adolescents, dual identifying adolescents, German-identifying adolescents with migrant heritage, and other-than-German-identifying adolescents. Students were marked as non-migratised majority adolescents if none of their parents and grandparents were born in a country other than Germany. These participants were not posed any further questions about ethnic/cultural self-identification. Only students who reported identifying equally as German and as a person from their family's origin country were considered dual identifiers, in line with previous studies in the German context [@jugert2018]. Students who reported having one or more (grand-)parent born abroad, but who identified only or more as German, were considered German-identifying adolescents with migrant heritage. Finally, students who viewed themselves as only or more as a person from their family's origin country were categorised as other-than-German-identifying adolescents. A robustness check was conducted in which students identifying as mostly German or mostly part of their family's origin country were included in the dual identifier category. Since identity is a dynamic construct, particularly in the adolescent phase of development, group identification was treated as a time-varying covariate.

**Control Variables**

Information about students' primary school, neighbourhood of residence, and specific classroom were used to control for contact opportunities that may affect the prevalence of intergroup friendship but are likely to be part of the social influence process of interest. Gender was included to control for the well-known tendency for gender homophily among adolescents.

## Methods

density, recip, transTrip, isolateNet?, altX for dual identifiers, sameX, diffXOutAct conditional on MajDI dyad? transTripX or diffXTransTrip or jumpXTransTrip. diffXTransTripX? diffXTransTrip = transitive closure i-h-j-i where i and j have different covariate values, while transTripX = transitive closure i-h-j-i weighted by covariate value of h I need to ask Jochem about this.

altX (sum of the covariate over all actors to whom i has a tie) interacted with sameX

covariate-difference or covariate-related difference (diffX), defined by the alter-minus
ego difference of the covariate over all actors to whom i has a tie,

**Question**: it seems like the effects are mostly based on similarity/difference, not specific combinations. Does this mean that instead of marking identities as different levels of the same variable, I should make one binary variable of dual identity?

Okay based on [@chen2026] I think this is the case. To investigate Maj student preferences for certain groups, they compared the alter effect of DIs to the alter effect of Mono-Mins.

In that case, I have four identity variables:

Dual identifier? 0/1/NA

Majority? 0/1/NA

Heritage identifier? 0/1/NA

Migrantised German? 0/1/NA

In this case, we include altX Dual, and interact it with sameX Maj to see if the number of dual identifying friends influences majority students' tendency to befriend other majority students (as well as non-majority students to befriend other non-majority students). Also interact with X to see if the influence of befriending a dual identifier differs based on students' own identity.

OR: make one binary dual identity variable, and one ordinal identity variable that includes all groups as different levels. Then interact altX Dual with simX identity. Answers the question: does the number of dual identifying friends influence students' tendency to befriend students with an identity more similar to their own. Still, potential of interacting with X as well. –\> currently, this would be my choice I think

## References
